
name: "Static Analysis"

on:
    pull_request:
        branches:
            - "*.*"
            - "master"
    push:
        branches:
            - "*.*"
            - "master"
            - "*_actions"

env:
    PIMCORE_PROJECT_ROOT: ${{ github.workspace }}
    PIMCORE_ENVIRONMENT: test
    PIMCORE_TEST: 1
    PIMCORE_TEST_DB_DSN: "mysql://root@127.0.0.1:33006/pimcore_test"
    PIMCORE_TEST_REDIS_DSN: "redis://127.0.0.1:63379"

jobs:
    static-analysis-phpstan:
        name: "Static Analysis with PHPStan"
        runs-on: "ubuntu-20.04"

        strategy:
            matrix:
                dependencies:
                    - "lowest"
                    - "highest"
                php-version:
                    - "8.0"

        services:
            redis:
                image: redis
                ports:
                    - 63379:6379
            mariadb:
                image: "mariadb:10.5"
                ports:
                    - 33006:3306
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes

        steps:
            - name: "Checkout code"
              uses: "actions/checkout@v2"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  coverage: "none"
                  php-version: "${{ matrix.php-version }}"

            - name: "Setup Pimcore environment"
              run: |
                  .github/ci/scripts/setup-pimcore-environment.sh

            - name: "Install dependencies with Composer"
              uses: "ramsey/composer-install@v1"
              with:
                  dependency-versions: "${{ matrix.dependencies }}"

            - name: "Run a static analysis with phpstan/phpstan"
              run: "vendor/bin/phpstan analyse -c .github/ci/files/phpstan.actions.neon bundles/ lib/ models/ -l 3 --memory-limit=-1 --generate-baseline"

            - name: "Generate baseline with phpstan/phpstan"
              run: "cat /home/runner/work/pimcore/pimcore/phpstan-baseline.neon"

            - name: "Dump var/classes"
              run: "ls /home/runner/work/pimcore/pimcore"

            - name: "Dump checked-in baseline"
              run: "cat /home/runner/work/pimcore/pimcore/phpstan-baseline-new.neon"

            - name: "Restore baseline"
              run: "cp -f  /home/runner/work/pimcore/pimcore/phpstan-baseline-new.neon /home/runner/work/pimcore/pimcore/phpstan-baseline.neon"

            - name: "Run a static analysis with phpstan/phpstan"
              run: "vendor/bin/phpstan analyse -c .github/ci/files/phpstan.actions.neon bundles/ lib/ models/ -l 3 --memory-limit=-1"